_target_: src.datamodules.caser_datamodule.SantanderDataModule

data_dir: ${data_dir}  # data_dir is specified in config.yaml
dataset_name: ${dataset_name} 
dataset_name_test: ${dataset_name_test} 
batch_size: ${batch_size}
num_workers: 0
pin_memory: False
sample_size: 2000
min_data_points: 17
seed: 0
sequence_length: 5
target_length: 1
neg_samples: 3