_target_: src.models.caser.CaserModel

data_dir: ${data_dir}  # data_dir is specified in config.yaml
dataset_name: ${dataset_name} 
dataset_name_test: ${dataset_name_test} 
L: 5
d: 50
nh: 16
nv: 4
drop: 0.5
ac_conv: 'relu'
ac_fc: 'relu'
l2: 1e-6
learning_rate: 1e-3


